<a href="https://colab.research.google.com/github/SPelaez122/Proyecto-NLP-Fine-Tuning/blob/main/Proyecto_NLP_Fine_Tuning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
! pip install transformers datasets evaluate accelerate

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.13.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.29.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.11.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.10.0+cu128)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.13.5)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.24.2)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2026.4.22)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=2.0.0->accelerate) (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2026.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.1.2)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 6.1 MB/s eta 0:00:00
Installing collected packages: evaluate
Successfully installed evaluate-0.4.6

In [2]:
from huggingface_hub import notebook_login

notebook_login()

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

#Descripcion de los datasets y los problemas-tareas asociados



*   **Sequence Classification:** El dataset que escogi llamado AI-human-text, tiene textos como entrada, y el problema sera clasificarlos en dos simples clases, si este fue escrito por un humano o una IA, por lo tanto el output sera binario, 0 para humano, 1 para IA. Tiene mas de 400k registros.
*   **Sequence Labeling:** El dataset llamado ner_movie, tiene textos como entrada describiendo peliculas, y el problema sera darle un label e infentificar que describe la palabra, ya sea un actor, el plot de la pelicula o una opinion, el output sera una lista con los labels de cada token en la oracion.
*   **Sequence to sequence:** Utilizare el dataset llamado arxiv-summarization, tiene papers del repositorio arxiv como entrada , y el problema sera hacer un resumen de este paper, como un tipo abstract, muy importante en este tipo de publicaciones. El output es lo que se esperaria que se resuma.

In [3]:
from datasets import load_dataset

ai_to_human = load_dataset("andythetechnerd03/AI-human-text")
ner_movie = load_dataset("ttxy/ner_movie")
arxiv_summarization = load_dataset("ccdv/arxiv-summarization", "section")

README.md:   0%|          | 0.00/808 [00:00<?, ?B/s]

data/train-00000-of-00003.parquet:   0%|          | 0.00/181M [00:00<?, ?B/s]

data/train-00001-of-00003.parquet:   0%|          | 0.00/181M [00:00<?, ?B/s]

data/train-00002-of-00003.parquet:   0%|          | 0.00/181M [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/28.5M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/462873 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/24362 [00:00<?, ? examples/s]

README.md:   0%|          | 0.00/147 [00:00<?, ?B/s]

dataset_infos.json:   0%|          | 0.00/431 [00:00<?, ?B/s]

train.csv:   0%|          | 0.00/1.79M [00:00<?, ?B/s]

test.csv:   0%|          | 0.00/441k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/7816 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1953 [00:00<?, ? examples/s]

README.md: 0.00B [00:00, ?B/s]

section/train-00000-of-00015.parquet:   0%|          | 0.00/230M [00:00<?, ?B/s]

section/train-00001-of-00015.parquet:   0%|          | 0.00/228M [00:00<?, ?B/s]

section/train-00002-of-00015.parquet:   0%|          | 0.00/228M [00:00<?, ?B/s]

section/train-00003-of-00015.parquet:   0%|          | 0.00/227M [00:00<?, ?B/s]

section/train-00004-of-00015.parquet:   0%|          | 0.00/226M [00:00<?, ?B/s]

section/train-00005-of-00015.parquet:   0%|          | 0.00/227M [00:00<?, ?B/s]

section/train-00006-of-00015.parquet:   0%|          | 0.00/229M [00:00<?, ?B/s]

section/train-00007-of-00015.parquet:   0%|          | 0.00/230M [00:00<?, ?B/s]

section/train-00008-of-00015.parquet:   0%|          | 0.00/230M [00:00<?, ?B/s]

section/train-00009-of-00015.parquet:   0%|          | 0.00/228M [00:00<?, ?B/s]

section/train-00010-of-00015.parquet:   0%|          | 0.00/229M [00:00<?, ?B/s]

section/train-00011-of-00015.parquet:   0%|          | 0.00/231M [00:00<?, ?B/s]

section/train-00012-of-00015.parquet:   0%|          | 0.00/230M [00:00<?, ?B/s]

section/train-00013-of-00015.parquet:   0%|          | 0.00/230M [00:00<?, ?B/s]

section/train-00014-of-00015.parquet:   0%|          | 0.00/235M [00:00<?, ?B/s]

section/validation-00000-of-00001.parque(…):   0%|          | 0.00/105M [00:00<?, ?B/s]

section/test-00000-of-00001.parquet:   0%|          | 0.00/105M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/203037 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/6436 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/6440 [00:00<?, ? examples/s]

### Analisis exploratorio

#### ai_to_human Dataset (Sequence Classification)

In [ ]:
# Display information about the dataset structure
print(ai_to_human)

print("\nExamples from AI-human-text dataset (first 5):\n")
for i in range(5):
    data = ai_to_human["train"][i]
    print(data)

DatasetDict({
    train: Dataset({
        features: ['text', 'generated'],
        num_rows: 462873
    })
    test: Dataset({
        features: ['text', 'generated'],
        num_rows: 24362
    })
})

Examples from AI-human-text dataset (first 5):

{'text': 'studies have been proven that people are starting to not drive cars as much americans are buying fewer cars and getting fewer licenses there are several advantages to not driving cars everywhere beneficial implications for carbon emissions the environment and improves safetyvaubans streets in germany are completely car free people who do not drive cars any more and ride bikes walks or rides the tram are said to be happier this way a mother of two walks and rides her bikes everywhere with her kids and does not feel as tense and stressed as she did when she was drivingalso a huge advantage is it drastically reduces greenhouse gas emissions from tailpipes diesel fuel was banned in france since tax policies favored diesel over gasoline delivery companies complained of lost revenue but exceptions were made plugin cars hybrids and cars carrying three or more passengersin paris there were days of near record pollution so they enforced a partial driving ban to clear the air of the city april 2013 the number of miles driven per person was nearly 9 percent below average and equal to the country in january 1995 the rate of car ownership per household and per person came down two to three years before the downturn michael siva stated new york has a new bike sharing program and the skyrocketing bridges and tunnel tolls reflect people to want to not drive cars anymorea study last year found that driving by young people decreased 23 percent between 2001 and 2009 just shows you that the beneficial implications environment and easier way of saving money does make people want to start biking walking using a tram etc those examples i gave you are a few advantages of limiting car use', 'generated': 0}
{'text': 'i disagree with you ih twenty years the humber of cars ih use will be the same or even greater that it is today there are a humber of reasons why this is likely to be the case firstly the humber of people ih the world is growing so there will be more people who heed to get around secondly the technology behind cars is continuing to improve so they are getting more fuel efficient ahd driverfriehdly ahd finally the cost of owing a car is continuing to increase making it less affordable for more ahd more people to use themall of these factors are likely to lead to a rise ih the humber of cars oh the road ih twenty years time so i believe that you will be wrong ih your prediction ahd that the humber of cars ih use will be greater that it is today', 'generated': 1}
{'text': 'hey yall today were gonna talk about this cool idea that winston churchill had about success he said that its all about going through failure without losing your enthusiasm lime whoa right let me tell you why i thing this is so importantfirst lets define what success means success is lime you now achieving your goals and stuff but churchills idea is that its not just about reaching the top its about how you get there if youre going to fail you might as well fail with passion and determination yam now lime if youre gonna fall fall hard and get back up again dont just give up and be sad about itso why is this so important well let me tell you a little story last year i was trying out for the school play and i really wanted to get the lead role but lime i didnt get it and i was super sad about it i mean i cried and stuff but then i realized why am i crying i didnt get the part but i still tried my best and thats what matters i didnt lose my enthusiasm just because i didnt get what i wanted im still gonna meet on trying and one day ill get that lead roleand its not just about school stuff lime thing about it if you want to be a pro athlete youre going to get rejected a lot but if you lose your enthusiasm every time you get rejected youre never gonna made it you have to meet on going even when its hard and the same thing goes for any job or career you want youre going to face rejection and failure but if you dont lose your enthusiasm youll made it throughso in conclusion churchills idea about success is totally true its not just about reaching your goals its about how you get there if you go through failure without losing your enthusiasm youre way more likely to succeed in the long run and who knows you', 'generated': 1}
{'text': 'im going to start explaining and giving my opinion technology is one of the main reasons why the world is changing and accommodating with the necessities that the person have for example we live in a community that if everything is easier is better few years ago people had to walk hours or days to go somewhere on this days the transport is a lot easier because the technology had increasedyou can use or have your own car or youcan take the public transport and go everywhere without problems and if you want to go to another country you can because the air lines exist now and you can fly to go to the country you likeso technology have a positive effect because it is helping us to make our daily necessities at home or everywhere better a reason why i think that is because the future of the students is going to be with more opportunities to learn what they like without saying excuses the help of others is not going to be that necessary with technology in your hands nobody have to advocate for you with your problems and decisionstechnology is going to be increasing for example years ago you could not talk to your family or friends if they were too far away from you in that edge the only thing you could do was write a letter and send it through mail and then the people who was waiting for it has to wait like one or two months for having that note but all that had changed toowhen the telephone was invented people start buying and using that invent for the public in general the telephone start to be necessary for the people for emergencies like call the ambulance or call the police in case that something dangerous could be happenedyears before the history of the telephone became with new ideas like you can not just call with the telephone because is having be made it smart you can take pictures play read book and more today the telephone have a drastic change is nothing like the old phone is something different technology had changed our way to communicate and transport and a lot more', 'generated': 0}
{'text': 'limiting car usage can be very helpful not only to our environment but to our culture our ozone is slowly getting worse and worse every year a heavy contributor to the decay of the ozone layer is the greenhouse gasses like the ones we emit from our cars on a daily basis a society without cars could create a safer more time friendly and environmentally healthy communitythink of all the tragedies that have spawned from car crashes just this year in our local community a 16yearold boy was knocked off our local bridge and killed by a drunk driver our city is still recovering from this not a day goes by where i dont see a new person leaving flowers in his spot on the bridge in a society without cars this would never have to happen again think of all the potential lives that could be savedthink about how much time you spend in a car on the average day at least 30 minutes to an hour if you go to school a job or a sport if we didnt have to drive everywhere everything we needed would be compacted into walking distance life would be so much easier if you didnt have to stress about getting up early enough to catch the bus or for your friends mom to pick you up you could just casually walk out the door and be at your destination in no timelife without cars could be the change that our country needs improved environmental conditions safety improving drastically and your precious time being saved maybe life without cars wouldnt be as great as were making it out to be but how are we ever going to know if we dont try this change would be for the better and is exactly what america needs  ', 'generated': 0}

#### ner_movie Dataset (Sequence Labeling)

In [ ]:
# Display information about the dataset structure
print(ner_movie)

for i in range(5):
    data = ner_movie["train"][i]
    print(data)

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 7816
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 1953
    })
})
{'text': 'steve mcqueen provided a thrilling motorcycle chase in this greatest of all ww 2 prison escape movies', 'label': 'B-Actor,I-Actor,O,O,B-Plot,I-Plot,I-Plot,I-Plot,I-Plot,B-Opinion,I-Opinion,I-Opinion,B-Plot,I-Plot,I-Plot,I-Plot,I-Plot'}
{'text': 'liza minnelli and joel gray won oscars for their roles in this 1972 movie that follows nightclub entertainers in berlin as the nazis come to power', 'label': 'B-Actor,I-Actor,O,B-Actor,I-Actor,B-Award,I-Award,O,O,O,O,O,B-Year,O,B-Plot,I-Plot,I-Plot,I-Plot,I-Plot,I-Plot,I-Plot,I-Plot,I-Plot,I-Plot,I-Plot,I-Plot'}
{'text': 'what is that tom hanks and julia roberts movie about hanks who plays a down on his luck average guy who goes back to college and gets taught by roberts', 'label': 'O,O,O,B-Actor,I-Actor,O,B-Actor,I-Actor,O,O,B-Plot,I-Plot,I-Plot,I-Plot,I-Plot,I-Plot,I-Plot,I-Plot,I-Plot,I-Plot,I-Plot,I-Plot,I-Plot,I-Plot,I-Plot,I-Plot,I-Plot,I-Plot,I-Plot,I-Plot'}
{'text': 'what is the movie making fun of macgyver by re enacting scenes similar to his movies', 'label': 'O,O,O,O,B-Plot,I-Plot,I-Plot,I-Plot,I-Plot,I-Plot,I-Plot,I-Plot,I-Plot,I-Plot,I-Plot,I-Plot'}
{'text': 'i am thinking of an animated film based on a classic theodor geisel children s novel about a young boy s quest to save the trees', 'label': 'O,O,O,O,O,B-Genre,O,B-Origin,I-Origin,I-Origin,I-Origin,I-Origin,I-Origin,I-Origin,I-Origin,I-Origin,O,B-Plot,I-Plot,I-Plot,I-Plot,I-Plot,I-Plot,I-Plot,I-Plot,I-Plot'}

#### arxiv-summarization Dataset (Sequence to Sequence)

In [4]:
# Display information about the dataset structure
print(arxiv_summarization)

for i in range(5):
    data = arxiv_summarization["train"][i]
    print(data)

DatasetDict({
    train: Dataset({
        features: ['article', 'abstract'],
        num_rows: 203037
    })
    validation: Dataset({
        features: ['article', 'abstract'],
        num_rows: 6436
    })
    test: Dataset({
        features: ['article', 'abstract'],
        num_rows: 6440
    })
})

### Setting up Tokenizers and Models for Fine-tuning

#### 1. Sequence Classification (AI-human-text Dataset) - using DistilBERT

In [15]:
id2label = {0: "HUMAN", 1: "AI"}
label2id = {"HUMAN": 0, "AI": 1}

In [16]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

# Model checkpoint for sequence classification
model_checkpoint_ai_human = "distilbert-base-uncased"

# For AI-human classification (0 for human, 1 for AI)
num_labels_ai_human = 2

# Load the tokenizer
tokenizer_ai_human = AutoTokenizer.from_pretrained(model_checkpoint_ai_human)

# Load the model with a classification head
model_ai_human = AutoModelForSequenceClassification.from_pretrained(
    model_checkpoint_ai_human,
    num_labels=num_labels_ai_human,id2label=id2label, label2id=label2id
)

print(f"Tokenizer loaded for AI-human classification: {model_checkpoint_ai_human}")
print(f"Model for Sequence Classification loaded: {model_checkpoint_ai_human} with {num_labels_ai_human} labels")

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.bias   | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
pre_classifier.bias     | MISSING    |
pre_classifier.weight   | MISSING    |
classifier.weight       | MISSING    |
classifier.bias         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Tokenizer loaded for AI-human classification: distilbert-base-uncased
Model for Sequence Classification loaded: distilbert-base-uncased with 2 labels

#### 2. Sequence Labeling (ner_movie Dataset) - using DistilBERT

In [17]:
# Extract all unique NER tags from the 'label' column
all_labels_str = ner_movie['train']['label']
unique_labels = set()
for label_str in all_labels_str:
    # Split the comma-separated string and add to the set
    for label in label_str.split(','):
        unique_labels.add(label.strip())

# Sort the unique labels to ensure consistent mapping
label_names_ner_movie = sorted(list(unique_labels))

# Create id2label and label2id mappings
id2label_ner = {i: label for i, label in enumerate(label_names_ner_movie)}
label2id_ner = {label: i for i, label in enumerate(label_names_ner_movie)}

print("id2label for NER:", id2label_ner)
print("label2id for NER:", label2id_ner)
print(f"Number of labels for NER: {len(label_names_ner_movie)}")

id2label for NER: {0: 'B-Actor', 1: 'B-Award', 2: 'B-Character_Name', 3: 'B-Director', 4: 'B-Genre', 5: 'B-Opinion', 6: 'B-Origin', 7: 'B-Plot', 8: 'B-Quote', 9: 'B-Relationship', 10: 'B-Soundtrack', 11: 'B-Year', 12: 'I-Actor', 13: 'I-Award', 14: 'I-Character_Name', 15: 'I-Director', 16: 'I-Genre', 17: 'I-Opinion', 18: 'I-Origin', 19: 'I-Plot', 20: 'I-Quote', 21: 'I-Relationship', 22: 'I-Soundtrack', 23: 'I-Year', 24: 'O'}
label2id for NER: {'B-Actor': 0, 'B-Award': 1, 'B-Character_Name': 2, 'B-Director': 3, 'B-Genre': 4, 'B-Opinion': 5, 'B-Origin': 6, 'B-Plot': 7, 'B-Quote': 8, 'B-Relationship': 9, 'B-Soundtrack': 10, 'B-Year': 11, 'I-Actor': 12, 'I-Award': 13, 'I-Character_Name': 14, 'I-Director': 15, 'I-Genre': 16, 'I-Opinion': 17, 'I-Origin': 18, 'I-Plot': 19, 'I-Quote': 20, 'I-Relationship': 21, 'I-Soundtrack': 22, 'I-Year': 23, 'O': 24}
Number of labels for NER: 25

### Updating Model Loading for Sequence Labeling with Label Mappings

In [18]:
from transformers import AutoModelForTokenClassification

# Model checkpoint for sequence labeling (DistilBERT)
model_checkpoint_ner = "distilbert-base-uncased"

# Get the number of labels for the ner_movie dataset
# This should now be len(label_names_ner_movie)
num_labels_ner_movie = len(label_names_ner_movie)

# Load the model with a token classification head, providing id2label and label2id
model_ner_movie = AutoModelForTokenClassification.from_pretrained(
    model_checkpoint_ner,
    num_labels=num_labels_ner_movie,
    id2label=id2label_ner,
    label2id=label2id_ner
)

print(f"Tokenizer (reusing DistilBERT) loaded for NER: {model_checkpoint_ner}")
print(f"Model for Token Classification loaded: {model_checkpoint_ner} with {num_labels_ner_movie} labels")
print(f"NER Labels: {label_names_ner_movie}")

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertForTokenClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.bias   | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
classifier.weight       | MISSING    |
classifier.bias         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Tokenizer (reusing DistilBERT) loaded for NER: distilbert-base-uncased
Model for Token Classification loaded: distilbert-base-uncased with 25 labels
NER Labels: ['B-Actor', 'B-Award', 'B-Character_Name', 'B-Director', 'B-Genre', 'B-Opinion', 'B-Origin', 'B-Plot', 'B-Quote', 'B-Relationship', 'B-Soundtrack', 'B-Year', 'I-Actor', 'I-Award', 'I-Character_Name', 'I-Director', 'I-Genre', 'I-Opinion', 'I-Origin', 'I-Plot', 'I-Quote', 'I-Relationship', 'I-Soundtrack', 'I-Year', 'O']

#### 3. Sequence to Sequence (arxiv-summarization Dataset) - using T5

In [7]:
from transformers import AutoModelForSeq2SeqLM
from transformers import AutoTokenizer

# Model checkpoint for summarization (T5-small for efficiency)
model_checkpoint_summarization = "t5-small"

# Load the tokenizer
tokenizer_summarization = AutoTokenizer.from_pretrained(model_checkpoint_summarization)

# Load the model for sequence to sequence generation
model_summarization = AutoModelForSeq2SeqLM.from_pretrained(model_checkpoint_summarization)

print(f"Tokenizer loaded for summarization: {model_checkpoint_summarization}")
print(f"Model for Sequence to Sequence loaded: {model_checkpoint_summarization}")

config.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/242M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/131 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

Tokenizer loaded for summarization: t5-small
Model for Sequence to Sequence loaded: t5-small

### Metrica accuracy, f1 y funcion compute

In [8]:
!pip install seqeval

Collecting seqeval
  Downloading seqeval-1.2.2.tar.gz (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 1.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from seqeval) (2.0.2)
Requirement already satisfied: scikit-learn>=0.21.3 in /usr/local/lib/python3.12/dist-packages (from seqeval) (1.6.1)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.21.3->seqeval) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.21.3->seqeval) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.21.3->seqeval) (3.6.0)
Building wheels for collected packages: seqeval
  Building wheel for seqeval (setup.py) ... done
  Created wheel for seqeval: filename=seqeval-1.2.2-py3-none-any.whl size=16162 sha256=09de650122c89cf8465814b3092d217f9acdc9080e617ec9da37ef3c94958e33
  Stored in directory: /root/.cache/pip/wheels/5f/b8/73/0b2c1a76b701a677653dd79ece07cfabd7457989dbfbdcd8d7
Successfully built seqeval
Installing collected packages: seqeval
Successfully installed seqeval-1.2.2

In [9]:
!pip install rouge_score

Collecting rouge_score
  Downloading rouge_score-0.1.2.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from rouge_score) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (from rouge_score) (3.9.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rouge_score) (2.0.2)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from rouge_score) (1.17.0)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (8.3.3)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (4.67.3)
Building wheels for collected packages: rouge_score
  Building wheel for rouge_score (setup.py) ... done
  Created wheel for rouge_score: filename=rouge_score-0.1.2-py3-none-any.whl size=24934 sha256=3c2c16ea61f003ca08b87c87811459c2f9f41039f9ae150868898aaeacb65b99
  Stored in directory: /root/.cache/pip/wheels/85/9d/af/01feefbe7d55ef5468796f0c68225b6788e85d9d0a281e7a70
Successfully built rouge_score
Installing collected packages: rouge_score
Successfully installed rouge_score-0.1.2

In [10]:
import numpy as np
import evaluate

# Load the metrics globally
accuracy_metric = evaluate.load("accuracy")
f1_metric = evaluate.load("f1")
seqeval_metric = evaluate.load("seqeval")
rouge_metric = evaluate.load("rouge") # Load ROUGE metric for summarization

Downloading builder script: 0.00B [00:00, ?B/s]

Downloading builder script: 0.00B [00:00, ?B/s]

Downloading builder script: 0.00B [00:00, ?B/s]

Downloading builder script: 0.00B [00:00, ?B/s]

In [ ]:
def compute_metrics_classification(eval_pred):
    predictions, labels = eval_pred.predictions, eval_pred.label_ids
    if isinstance(predictions, tuple):
        predictions = predictions[0]
    predictions = np.argmax(predictions, axis=1)
    accuracy = accuracy_metric.compute(predictions=predictions, references=labels)
    f1 = f1_metric.compute(predictions=predictions, references=labels)
    return {"accuracy": accuracy["accuracy"], "f1": f1["f1"]}

In [ ]:
def compute_metrics_ner(eval_pred):
    predictions, labels = eval_pred.predictions, eval_pred.label_ids
    if isinstance(predictions, tuple):
        predictions = predictions[0]
    predictions = np.argmax(predictions, axis=2) # Get predicted label ID for each token

    true_labels = [[id2label_ner[l] for l in label_list if l != -100] for label_list in labels]
    true_predictions = [[id2label_ner[p] for (p, l) in zip(pred_list, label_list) if l != -100] for pred_list, label_list in zip(predictions, labels)]

    results = seqeval_metric.compute(predictions=true_predictions, references=true_labels)

    return {
        "precision": results["overall_precision"],
        "recall": results["overall_recall"],
        "f1": results["overall_f1"],
        "accuracy": results["overall_accuracy"],
    }

In [11]:
def compute_metrics_summarization(eval_pred):
    predictions, labels = eval_pred.predictions, eval_pred.label_ids
    if isinstance(predictions, tuple):
        predictions = predictions[0]

    # Convert logits (3D array) to predicted token IDs (2D array)
    predictions = np.argmax(predictions, axis=-1)

    decoded_preds = tokenizer_summarization.batch_decode(predictions, skip_special_tokens=True)
    labels = np.where(labels != -100, labels, tokenizer_summarization.pad_token_id)
    decoded_labels = tokenizer_summarization.batch_decode(labels, skip_special_tokens=True)

    result = rouge_metric.compute(predictions=decoded_preds, references=decoded_labels, use_stemmer=True)
    result = {key: value * 100 for key, value in result.items()}
    return result

### Tokenizing Datasets

In [ ]:
def tokenize_ai_human_function(examples):
    tokenized_inputs = tokenizer_ai_human(examples["text"], truncation=True)
    # Add the labels (the 'generated' column) to the tokenized inputs
    tokenized_inputs["labels"] = examples["generated"]
    return tokenized_inputs

tokenized_ai_human = ai_to_human.map(tokenize_ai_human_function, batched=True)

print("Tokenized AI-human-text dataset example:")
print(tokenized_ai_human["train"][0])

Map:   0%|          | 0/462873 [00:00<?, ? examples/s]

Map:   0%|          | 0/24362 [00:00<?, ? examples/s]

Tokenized AI-human-text dataset example:
{'text': 'studies have been proven that people are starting to not drive cars as much americans are buying fewer cars and getting fewer licenses there are several advantages to not driving cars everywhere beneficial implications for carbon emissions the environment and improves safetyvaubans streets in germany are completely car free people who do not drive cars any more and ride bikes walks or rides the tram are said to be happier this way a mother of two walks and rides her bikes everywhere with her kids and does not feel as tense and stressed as she did when she was drivingalso a huge advantage is it drastically reduces greenhouse gas emissions from tailpipes diesel fuel was banned in france since tax policies favored diesel over gasoline delivery companies complained of lost revenue but exceptions were made plugin cars hybrids and cars carrying three or more passengersin paris there were days of near record pollution so they enforced a partial driving ban to clear the air of the city april 2013 the number of miles driven per person was nearly 9 percent below average and equal to the country in january 1995 the rate of car ownership per household and per person came down two to three years before the downturn michael siva stated new york has a new bike sharing program and the skyrocketing bridges and tunnel tolls reflect people to want to not drive cars anymorea study last year found that driving by young people decreased 23 percent between 2001 and 2009 just shows you that the beneficial implications environment and easier way of saving money does make people want to start biking walking using a tram etc those examples i gave you are a few advantages of limiting car use', 'generated': 0, 'input_ids': [101, 2913, 2031, 2042, 10003, 2008, 2111, 2024, 3225, 2000, 2025, 3298, 3765, 2004, 2172, 4841, 2024, 9343, 8491, 3765, 1998, 2893, 8491, 15943, 2045, 2024, 2195, 12637, 2000, 2025, 4439, 3765, 7249, 15189, 13494, 2005, 6351, 11768, 1996, 4044, 1998, 24840, 3808, 3567, 19761, 3619, 4534, 1999, 2762, 2024, 3294, 2482, 2489, 2111, 2040, 2079, 2025, 3298, 3765, 2151, 2062, 1998, 4536, 18105, 7365, 2030, 12271, 1996, 12517, 2024, 2056, 2000, 2022, 19366, 2023, 2126, 1037, 2388, 1997, 2048, 7365, 1998, 12271, 2014, 18105, 7249, 2007, 2014, 4268, 1998, 2515, 2025, 2514, 2004, 9049, 1998, 13233, 2004, 2016, 2106, 2043, 2016, 2001, 4439, 9777, 2080, 1037, 4121, 5056, 2003, 2009, 21040, 13416, 16635, 3806, 11768, 2013, 5725, 24548, 2015, 7937, 4762, 2001, 7917, 1999, 2605, 2144, 4171, 6043, 12287, 7937, 2058, 13753, 6959, 3316, 10865, 1997, 2439, 6599, 2021, 11790, 2020, 2081, 13354, 2378, 3765, 23376, 1998, 3765, 4755, 2093, 2030, 2062, 5467, 2378, 3000, 2045, 2020, 2420, 1997, 2379, 2501, 10796, 2061, 2027, 16348, 1037, 7704, 4439, 7221, 2000, 3154, 1996, 2250, 1997, 1996, 2103, 2258, 2286, 1996, 2193, 1997, 2661, 5533, 2566, 2711, 2001, 3053, 1023, 3867, 2917, 2779, 1998, 5020, 2000, 1996, 2406, 1999, 2254, 2786, 1996, 3446, 1997, 2482, 6095, 2566, 4398, 1998, 2566, 2711, 2234, 2091, 2048, 2000, 2093, 2086, 2077, 1996, 2091, 22299, 2745, 9033, 3567, 3090, 2047, 2259, 2038, 1037, 2047, 7997, 6631, 2565, 1998, 1996, 3712, 16901, 20624, 3070, 7346, 1998, 5234, 9565, 2015, 8339, 2111, 2000, 2215, 2000, 2025, 3298, 3765, 4902, 2050, 2817, 2197, 2095, 2179, 2008, 4439, 2011, 2402, 2111, 10548, 2603, 3867, 2090, 2541, 1998, 2268, 2074, 3065, 2017, 2008, 1996, 15189, 13494, 4044, 1998, 6082, 2126, 1997, 7494, 2769, 2515, 2191, 2111, 2215, 2000, 2707, 28899, 3788, 2478, 1037, 12517, 4385, 2216, 4973, 1045, 2435, 2017, 2024, 1037, 2261, 12637, 1997, 14879, 2482, 2224, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'labels': 0}

In [ ]:
def tokenize_and_align_labels(examples):
    tokenized_inputs = tokenizer_ai_human(
        examples["text"],
        truncation=True,
    )

    labels = []
    for i, label_str in enumerate(examples["label"]):
        word_ids = tokenized_inputs.word_ids(batch_index=i)
        previous_word_idx = None
        label_ids = []
        # Convert string labels to integer IDs
        example_labels_ids = [label2id_ner[l.strip()] for l in label_str.split(',')]

        for word_idx in word_ids:
            if word_idx is None:
                label_ids.append(-100)
            elif word_idx != previous_word_idx:
                if word_idx < len(example_labels_ids): # Use example_labels_ids here
                    label_ids.append(example_labels_ids[word_idx])
                else:
                    # Fallback for cases where word_idx exceeds available example_labels_ids
                    # This could happen if the number of words from word_ids is more than the number of explicit labels.
                    label_ids.append(-100)
            else:
                label_ids.append(-100)
            previous_word_idx = word_idx

        labels.append(label_ids)

    tokenized_inputs["labels"] = labels
    return tokenized_inputs

# Apply the preprocessing function and remove original columns to ensure only tokenized data remains
tokenized_ner_movie = ner_movie.map(tokenize_and_align_labels, batched=True, remove_columns=ner_movie["train"].column_names)

print("Tokenized ner_movie dataset example (first example, showing all features):")
print(tokenized_ner_movie["train"][0])

Tokenized ner_movie dataset example (first example, showing all features):
{'input_ids': [101, 3889, 29265, 3024, 1037, 26162, 9055, 5252, 1999, 2023, 4602, 1997, 2035, 1059, 2860, 1016, 3827, 4019, 5691, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'labels': [-100, 0, 12, 24, 24, 7, 19, 19, 19, 19, 5, 17, 17, 7, -100, 19, 19, 19, 19, -100]}

In [12]:
def preprocess_function(examples):
    # Truncate article to 512 words before adding prefix and tokenizing
    truncated_articles = [" ".join(doc.split(' ')[:512]) for doc in examples["article"]]
    inputs = ["summarize: " + doc for doc in truncated_articles]
    model_inputs = tokenizer_summarization(inputs, truncation=True)

    # Truncate abstract to 128 words before tokenizing
    truncated_abstracts = [" ".join(abs_doc.split(' ')[:128]) for abs_doc in examples["abstract"]]
    labels = tokenizer_summarization(text_target=truncated_abstracts, truncation=True)

    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

# Use the complete arxiv_summarization dataset for tokenization
tokenized_arxiv_summarization_train = arxiv_summarization["train"].map(preprocess_function, batched=True)
tokenized_arxiv_summarization_test = arxiv_summarization["test"].map(preprocess_function, batched=True)

tokenized_arxiv_summarization = {
    "train": tokenized_arxiv_summarization_train,
    "test": tokenized_arxiv_summarization_test
}

print("Tokenized arxiv-summarization dataset example (train split):")
print(tokenized_arxiv_summarization["train"][0])

Map:   0%|          | 0/203037 [00:00<?, ? examples/s]

Map:   0%|          | 0/6440 [00:00<?, ? examples/s]

Tokenized arxiv-summarization dataset example (train split):

# Training tests

### Data Collators for Each Task

In [19]:
from transformers import DataCollatorWithPadding, DataCollatorForTokenClassification, DataCollatorForSeq2Seq

# Data collator for AI-human text (Sequence Classification)
data_collator_ai_human = DataCollatorWithPadding(tokenizer=tokenizer_ai_human)
print("Data collator for AI-human text (sequence classification) created.")

# Data collator for NER movie (Token Classification)
data_collator_ner_movie = DataCollatorForTokenClassification(tokenizer=tokenizer_ai_human)
print("Data collator for NER movie (token classification) created.")

# Data collator for Arxiv Summarization (Sequence to Sequence)
data_collator_summarization = DataCollatorForSeq2Seq(tokenizer=tokenizer_summarization, model=model_summarization)
print("Data collator for Arxiv Summarization (sequence to sequence) created.")

Data collator for AI-human text (sequence classification) created.
Data collator for NER movie (token classification) created.
Data collator for Arxiv Summarization (sequence to sequence) created.

### Hyperparameter Tuning Tests on Sampled Data

#### Task 1: AI-human-text (Sequence Classification)

In [ ]:
from transformers import TrainingArguments, Trainer

# Sample a small subset of the tokenized AI-human dataset
sampled_ai_human_train = tokenized_ai_human["train"].shuffle(seed=42).select(range(1000))
sampled_ai_human_eval = tokenized_ai_human["test"].shuffle(seed=42).select(range(1000))

print(f"Sampled AI-human train dataset size: {len(sampled_ai_human_train)}")
print(f"Sampled AI-human eval dataset size: {len(sampled_ai_human_eval)}")

# Define a list of learning rates to test
learning_rates = [2e-5, 2e-4, 2e-3, 2e-2, 2e-1]

for lr in learning_rates:
    print(f"\n--- Starting training for AI-human text classification with learning rate: {lr} ---")

    # Define TrainingArguments for AI-human text with the current learning rate
    training_args_ai_human = TrainingArguments(
        output_dir=f"./results_ai_human_classification_lr_{lr}", # Unique output directory for each LR
        learning_rate=lr,
        per_device_train_batch_size=16,
        per_device_eval_batch_size=16,
        num_train_epochs=2, # Number of training epochs
        weight_decay=0.01,
        eval_strategy="epoch", # Evaluate at the end of each epoch
        save_strategy="epoch", # Save checkpoint at the end of each epoch
        load_best_model_at_end=True, # Load the best model after training
        push_to_hub=False, # Set to True if you want to push to Hugging Face Hub
        report_to="none" # Disable logging to external services for quick tests
    )

    # Initialize Trainer for AI-human text
    trainer_ai_human = Trainer(
        model=model_ai_human, # Re-using the same model instance, which will be reset implicitly or fine-tuned further
        args=training_args_ai_human,
        train_dataset=sampled_ai_human_train,
        eval_dataset=sampled_ai_human_eval,
        data_collator=data_collator_ai_human,
        compute_metrics=compute_metrics_classification,
    )

    # Train the model
    print(f"Starting training for AI-human text classification with LR={lr}...")
    trainer_ai_human.train()
    print(f"Finished training for AI-human text classification with LR={lr}.")

print("\n--- Completed all learning rate experiments for AI-human text classification. ---")

Sampled AI-human train dataset size: 1000
Sampled AI-human eval dataset size: 1000

--- Starting training for AI-human text classification with learning rate: 2e-05 ---
Starting training for AI-human text classification with LR=2e-05...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.weight', 'distilbert.embeddings.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.beta', 'distilbert.embeddings.LayerNorm.gamma'].

Finished training for AI-human text classification with LR=2e-05.

--- Starting training for AI-human text classification with learning rate: 0.0002 ---
Starting training for AI-human text classification with LR=0.0002...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.weight', 'distilbert.embeddings.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.beta', 'distilbert.embeddings.LayerNorm.gamma'].

Finished training for AI-human text classification with LR=0.0002.

--- Starting training for AI-human text classification with learning rate: 0.002 ---
Starting training for AI-human text classification with LR=0.002...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.weight', 'distilbert.embeddings.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.beta', 'distilbert.embeddings.LayerNorm.gamma'].

Finished training for AI-human text classification with LR=0.002.

--- Starting training for AI-human text classification with learning rate: 0.02 ---
Starting training for AI-human text classification with LR=0.02...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.weight', 'distilbert.embeddings.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.beta', 'distilbert.embeddings.LayerNorm.gamma'].

Finished training for AI-human text classification with LR=0.02.

--- Starting training for AI-human text classification with learning rate: 0.2 ---
Starting training for AI-human text classification with LR=0.2...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.weight', 'distilbert.embeddings.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.beta', 'distilbert.embeddings.LayerNorm.gamma'].

Finished training for AI-human text classification with LR=0.2.

--- Completed all learning rate experiments for AI-human text classification. ---

#### Task 2: ner_movie (Token Classification)

In [ ]:
from transformers import TrainingArguments, Trainer

# Sample a small subset of the tokenized NER movie dataset
sampled_ner_movie_train = tokenized_ner_movie["train"].shuffle(seed=42).select(range(1000))
sampled_ner_movie_eval = tokenized_ner_movie["test"].shuffle(seed=42).select(range(1000))

print(f"Sampled NER movie train dataset size: {len(sampled_ner_movie_train)}")
print(f"Sampled NER movie eval dataset size: {len(sampled_ner_movie_eval)}")

# Define a list of learning rates to test
learning_rates = [2e-5, 2e-4, 2e-3]

for lr in learning_rates:
    print(f"\n--- Starting training for NER movie token classification with learning rate: {lr} ---")

    # Define TrainingArguments for NER movie with the current learning rate
    training_args_ner_movie = TrainingArguments(
        output_dir=f"./results_ner_movie_token_classification_lr_{lr}", # Unique output directory for each LR
        learning_rate=lr,
        per_device_train_batch_size=16,
        per_device_eval_batch_size=16,
        num_train_epochs=2,
        weight_decay=0.01,
        eval_strategy="epoch",
        save_strategy="epoch",
        load_best_model_at_end=True,
        push_to_hub=False,
        report_to="none"
    )

    # Initialize Trainer for NER movie
    trainer_ner_movie = Trainer(
        model=model_ner_movie, # Re-using the same model instance, which will be reset implicitly or fine-tuned further
        args=training_args_ner_movie,
        train_dataset=sampled_ner_movie_train,
        eval_dataset=sampled_ner_movie_eval,
        data_collator=data_collator_ner_movie,
        compute_metrics=compute_metrics_ner,
    )

    # Train the model
    print(f"Starting training for NER movie token classification with LR={lr}...")
    trainer_ner_movie.train()
    print(f"Finished training for NER movie token classification with LR={lr}.")

print("\n--- Completed all learning rate experiments for NER movie token classification. ---")

Sampled NER movie train dataset size: 1000
Sampled NER movie eval dataset size: 1000

--- Starting training for NER movie token classification with learning rate: 2e-05 ---
Starting training for NER movie token classification with LR=2e-05...

/usr/local/lib/python3.12/dist-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.weight', 'distilbert.embeddings.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.beta', 'distilbert.embeddings.LayerNorm.gamma'].

Finished training for NER movie token classification with LR=2e-05.

--- Starting training for NER movie token classification with learning rate: 0.0002 ---
Starting training for NER movie token classification with LR=0.0002...

/usr/local/lib/python3.12/dist-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.weight', 'distilbert.embeddings.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.beta', 'distilbert.embeddings.LayerNorm.gamma'].

Finished training for NER movie token classification with LR=0.0002.

--- Starting training for NER movie token classification with learning rate: 0.002 ---
Starting training for NER movie token classification with LR=0.002...

/usr/local/lib/python3.12/dist-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.weight', 'distilbert.embeddings.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.beta', 'distilbert.embeddings.LayerNorm.gamma'].

Finished training for NER movie token classification with LR=0.002.

--- Completed all learning rate experiments for NER movie token classification. ---

#### Task 3: arxiv-summarization (Sequence to Sequence)

In [ ]:
# Sample a small subset of the tokenized Arxiv summarization dataset
sampled_arxiv_summarization_train = tokenized_arxiv_summarization["train"].shuffle(seed=42).select(range(100))
sampled_arxiv_summarization_eval = tokenized_arxiv_summarization["test"].shuffle(seed=42).select(range(100))

print(f"Sampled Arxiv summarization train dataset size: {len(sampled_arxiv_summarization_train)}")
print(f"Sampled Arxiv summarization eval dataset size: {len(sampled_arxiv_summarization_eval)}")

# Define a list of learning rates to test
learning_rates = [2e-5, 2e-4, 2e-3]

for lr in learning_rates:
    print(f"\n--- Starting training for Arxiv summarization with learning rate: {lr} ---")

    # Define TrainingArguments for Arxiv summarization with the current learning rate
    training_args_summarization = TrainingArguments(
        output_dir=f"./results_arxiv_summarization_lr_{lr}", # Unique output directory for each LR
        learning_rate=lr,
        per_device_train_batch_size=1, # Minimum batch size
        per_device_eval_batch_size=1,  # Minimum batch size
        gradient_accumulation_steps=4, # Accumulate gradients over 4 steps to simulate a batch size of 4
        num_train_epochs=2,
        weight_decay=0.01,
        eval_strategy="epoch",
        save_strategy="epoch",
        load_best_model_at_end=True,
        push_to_hub=False,
        report_to="none",
        fp16=True # Enable mixed-precision training
        # Removed predict_with_generate=True as it's not an argument for TrainingArguments
    )

    # Initialize Trainer for Arxiv summarization
    trainer_summarization = Trainer(
        model=model_summarization, # Re-using the same model instance, which will be reset implicitly or fine-tuned further
        args=training_args_summarization,
        train_dataset=sampled_arxiv_summarization_train,
        eval_dataset=sampled_arxiv_summarization_eval,
        data_collator=data_collator_summarization,
        compute_metrics=compute_metrics_summarization,
    )

    # Train the model
    print(f"Starting training for Arxiv summarization with LR={lr}...")
    trainer_summarization.train()
    print(f"Finished training for Arxiv summarization with LR={lr}.")

print("\n--- Completed all learning rate experiments for Arxiv summarization. ---")

Sampled Arxiv summarization train dataset size: 100
Sampled Arxiv summarization eval dataset size: 100

--- Starting training for Arxiv summarization with learning rate: 2e-05 ---
Starting training for Arxiv summarization with LR=2e-05...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['encoder.embed_tokens.weight', 'decoder.embed_tokens.weight', 'lm_head.weight'].

Finished training for Arxiv summarization with LR=2e-05.

--- Starting training for Arxiv summarization with learning rate: 0.0002 ---
Starting training for Arxiv summarization with LR=0.0002...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['encoder.embed_tokens.weight', 'decoder.embed_tokens.weight', 'lm_head.weight'].

Finished training for Arxiv summarization with LR=0.0002.

--- Starting training for Arxiv summarization with learning rate: 0.002 ---
Starting training for Arxiv summarization with LR=0.002...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['encoder.embed_tokens.weight', 'decoder.embed_tokens.weight', 'lm_head.weight'].

Finished training for Arxiv summarization with LR=0.002.

--- Completed all learning rate experiments for Arxiv summarization. ---

# Entrenamiento final

#### Task 1: AI-human-text (Sequence Classification) with 50k training samples

In [ ]:
from transformers import TrainingArguments, Trainer

# Sample the specified subset of the tokenized AI-human dataset
sampled_ai_human_train_final = tokenized_ai_human["train"].shuffle(seed=42).select(range(min(50000, len(tokenized_ai_human["train"]))));
sampled_ai_human_eval_final = tokenized_ai_human["test"].shuffle(seed=42).select(range(min(5000, len(tokenized_ai_human["test"])))); # Keeping eval small for quick checks

print(f"Sampled AI-human train dataset size: {len(sampled_ai_human_train_final)}")
print(f"Sampled AI-human eval dataset size: {len(sampled_ai_human_eval_final)}")

# Define a list of learning rates to test
learning_rates_ai_human = [2e-5]

for lr in learning_rates_ai_human:
    print(f"\n--- Starting final training for AI-human text classification with learning rate: {lr} ---")

    # Define TrainingArguments for AI-human text with the current learning rate
    training_args_ai_human_final = TrainingArguments(
        output_dir=f"./results_ai_human_classification_final_lr_{lr}", # Unique output directory for each LR
        learning_rate=lr,
        per_device_train_batch_size=16,
        per_device_eval_batch_size=16,
        num_train_epochs=2, # Number of training epochs
        weight_decay=0.01,
        eval_strategy="epoch", # Evaluate at the end of each epoch
        save_strategy="epoch", # Save checkpoint at the end of each epoch
        load_best_model_at_end=True, # Load the best model after training
        push_to_hub=True, # Set to True if you want to push to Hugging Face Hub
        report_to="none" # Disable logging to external services for quick tests
    )

    # Initialize Trainer for AI-human text
    trainer_ai_human_final = Trainer(
        model=model_ai_human, # Re-using the same model instance, which will be reset implicitly or fine-tuned further
        args=training_args_ai_human_final,
        train_dataset=sampled_ai_human_train_final,
        eval_dataset=sampled_ai_human_eval_final,
        data_collator=data_collator_ai_human,
        compute_metrics=compute_metrics_classification,
    )

    # Train the model
    print(f"Starting training for AI-human text classification with LR={lr}...")
    trainer_ai_human_final.train()
    print(f"Finished training for AI-human text classification with LR={lr}.")

print("\n--- Completed all final learning rate experiments for AI-human text classification. ---")

Sampled AI-human train dataset size: 50000
Sampled AI-human eval dataset size: 5000

--- Starting final training for AI-human text classification with learning rate: 2e-05 ---
Starting training for AI-human text classification with LR=2e-05...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.weight', 'distilbert.embeddings.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.beta', 'distilbert.embeddings.LayerNorm.gamma'].

Finished training for AI-human text classification with LR=2e-05.

--- Completed all final learning rate experiments for AI-human text classification. ---

In [ ]:
trainer_ai_human_final.push_to_hub()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...r_2e-05/training_args.bin: 100%|##########| 5.20kB / 5.20kB

  ...r_2e-05/model.safetensors:   6%|5         | 15.9MB /  268MB

CommitInfo(commit_url='https://huggingface.co/RockSkull/results_ai_human_classification_final_lr_2e-05/commit/9f529579746f23ac4fe02ddbd2746119c1d7071a', commit_message='End of training', commit_description='', oid='9f529579746f23ac4fe02ddbd2746119c1d7071a', pr_url=None, repo_url=RepoUrl('https://huggingface.co/RockSkull/results_ai_human_classification_final_lr_2e-05', endpoint='https://huggingface.co', repo_type='model', repo_id='RockSkull/results_ai_human_classification_final_lr_2e-05'), pr_revision=None, pr_num=None)

#### Task 2: ner_movie (Token Classification) with full dataset

In [ ]:
from transformers import TrainingArguments, Trainer

# Use the complete tokenized NER movie dataset
sampled_ner_movie_train_final = tokenized_ner_movie["train"]
sampled_ner_movie_eval_final = tokenized_ner_movie["test"]

print(f"Sampled NER movie train dataset size: {len(sampled_ner_movie_train_final)}")
print(f"Sampled NER movie eval dataset size: {len(sampled_ner_movie_eval_final)}")

# Define a list of learning rates to test
learning_rates_ner = [2e-4]

for lr in learning_rates_ner:
    print(f"\n--- Starting final training for NER movie token classification with learning rate: {lr} ---")

    # Define TrainingArguments for NER movie with the current learning rate
    training_args_ner_movie_final = TrainingArguments(
        output_dir=f"./results_ner_movie_token_classification_final_lr_{lr}", # Unique output directory for each LR
        learning_rate=lr,
        per_device_train_batch_size=16,
        per_device_eval_batch_size=16,
        num_train_epochs=2,
        weight_decay=0.01,
        eval_strategy="epoch",
        save_strategy="epoch",
        load_best_model_at_end=True,
        push_to_hub=True,
        report_to="none"
    )

    # Initialize Trainer for NER movie
    trainer_ner_movie_final = Trainer(
        model=model_ner_movie, # Re-using the same model instance, which will be reset implicitly or fine-tuned further
        args=training_args_ner_movie_final,
        train_dataset=sampled_ner_movie_train_final,
        eval_dataset=sampled_ner_movie_eval_final,
        data_collator=data_collator_ner_movie,
        compute_metrics=compute_metrics_ner,
    )

    # Train the model
    print(f"Starting training for NER movie token classification with LR={lr}...")
    trainer_ner_movie_final.train()
    print(f"Finished training for NER movie token classification with LR={lr}.")

print("\n--- Completed all final learning rate experiments for NER movie token classification. ---")

Sampled NER movie train dataset size: 7816
Sampled NER movie eval dataset size: 1953

--- Starting final training for NER movie token classification with learning rate: 0.0002 ---
Starting training for NER movie token classification with LR=0.0002...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.weight', 'distilbert.embeddings.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.beta', 'distilbert.embeddings.LayerNorm.gamma'].

Finished training for NER movie token classification with LR=0.0002.

--- Completed all final learning rate experiments for NER movie token classification. ---

In [ ]:
trainer_ner_movie_final.push_to_hub()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ..._0.0002/training_args.bin: 100%|##########| 5.20kB / 5.20kB

  ..._0.0002/model.safetensors:  42%|####2     |  112MB /  266MB

CommitInfo(commit_url='https://huggingface.co/RockSkull/results_ner_movie_token_classification_final_lr_0.0002/commit/8307c92d771e7046481ea86089bd36bec1dbd0d5', commit_message='End of training', commit_description='', oid='8307c92d771e7046481ea86089bd36bec1dbd0d5', pr_url=None, repo_url=RepoUrl('https://huggingface.co/RockSkull/results_ner_movie_token_classification_final_lr_0.0002', endpoint='https://huggingface.co', repo_type='model', repo_id='RockSkull/results_ner_movie_token_classification_final_lr_0.0002'), pr_revision=None, pr_num=None)

#### Task 3: arxiv-summarization (Sequence to Sequence) with 50k training samples

In [20]:
from transformers import TrainingArguments, Trainer

# Sample the specified subset of the tokenized Arxiv summarization dataset
sampled_arxiv_summarization_train_final = tokenized_arxiv_summarization["train"].shuffle(seed=42).select(range(min(50000, len(tokenized_arxiv_summarization["train"]))));
sampled_arxiv_summarization_eval_final = tokenized_arxiv_summarization["test"].shuffle(seed=42).select(range(min(6000, len(tokenized_arxiv_summarization["test"])))); # Keeping eval small for quick checks

print(f"Sampled Arxiv summarization train dataset size: {len(sampled_arxiv_summarization_train_final)}")
print(f"Sampled Arxiv summarization eval dataset size: {len(sampled_arxiv_summarization_eval_final)}")

# Define a list of learning rates to test
learning_rates_summarization = [2e-4]

for lr in learning_rates_summarization:
    print(f"\n--- Starting final training for Arxiv summarization with learning rate: {lr} ---")

    # Define TrainingArguments for Arxiv summarization with the current learning rate
    training_args_summarization_final = TrainingArguments(
        output_dir=f"./results_arxiv_summarization_final_lr_{lr}", # Unique output directory for each LR
        learning_rate=lr,
        per_device_train_batch_size=1, # Minimum batch size
        per_device_eval_batch_size=1,  # Minimum batch size
        gradient_accumulation_steps=4, # Accumulate gradients over 4 steps to simulate a batch size of 4
        num_train_epochs=2,
        weight_decay=0.01,
        eval_strategy="epoch",
        save_strategy="epoch",
        load_best_model_at_end=True,
        push_to_hub=True,
        report_to="none",
        fp16=True # Enable mixed-precision training
    )

    # Initialize Trainer for Arxiv summarization
    trainer_summarization_final = Trainer(
        model=model_summarization, # Re-using the same model instance, which will be reset implicitly or fine-tuned further
        args=training_args_summarization_final,
        train_dataset=sampled_arxiv_summarization_train_final,
        eval_dataset=sampled_arxiv_summarization_eval_final,
        data_collator=data_collator_summarization,
        compute_metrics=compute_metrics_summarization
    )

    # Train the model
    print(f"Starting training for Arxiv summarization with LR={lr}...")
    trainer_summarization_final.train()
    print(f"Finished training for Arxiv summarization with LR={lr}.")

print("\n--- Completed all final learning rate experiments for Arxiv summarization. ---")

Sampled Arxiv summarization train dataset size: 50000
Sampled Arxiv summarization eval dataset size: 6000

--- Starting final training for Arxiv summarization with learning rate: 0.0002 ---
Starting training for Arxiv summarization with LR=0.0002...

OutOfMemoryError: CUDA out of memory. Tried to allocate 6.47 GiB. GPU 0 has a total capacity of 14.56 GiB of which 6.42 GiB is free. Including non-PyTorch memory, this process has 8.14 GiB memory in use. Of the allocated memory 7.35 GiB is allocated by PyTorch, and 675.83 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)